title: Homeless and Housing Resource Center (HHRC)
meta: 
  description: Providing high-quality, no-cost training for health and housing professionals in evidenced-based practices that contribute to housing stability, recovery, and an end to homelessness.
highlight: We’re excited to bring you cutting-edge training related to housing and homelessness beginning in December 2020.
partners:
  - name: Partner Name
    link: http://www.google.com
    image: samhsa-logo.png
  - name: Partner Name
    link: http://www.google.com
    image: samhsa-logo.png
  - name: Partner Name
    link: http://www.google.com
    image: samhsa-logo.png
  - name: Partner Name
    link: http://www.google.com
    image: samhsa-logo.png
listserv:
  prompt: Sign up to the HHRC listserv to be the first to hear about new trainings and resources!  
  link: https://signup.e2ma.net/signup/1931256/1922613/
joinUs:
  formScriptLink: https://form.jotform.com/jsform/203515073000033  